### ISSUE TITLE
Agent does connect to some node's not all (armv7l /x64 mixed swarm)

### ISSUE THREAD

**Issue by xRmg** [portainer/agent#100]
**Bug description**
I have a swarm of 5 nodes (4x linux armv7l, 1 linux x86_64 ), when launching the agent stack the armv7l nodes join each other but not the linux x86_64 node

**Expected behavior**
I expect all agents to connect to each other irregardless of architecture.

**Steps to reproduce the issue:**
deploy stack with the following compose file:

```
version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer_agent:
    driver: overlay
    attachable: true
```

amd64 node (manager)
``` 
2019/11/12 15:04:34 [INFO] [main] [message: Agent running on a Swarm cluster node. Running in cluster mode]
2019/11/12 15:04:37 [INFO] serf: EventMemberJoin: gen8-96cb79962f2b 10.0.5.6
2019/11/12 15:05:18 [INFO] [http] [server_addr: 0.0.0.0] [server_port: 9001] [secured: true] [api_version: 1.5.1] [message: Starting Agent API server]
```

arm64 node (workers)
```
2019/11/12 15:04:33 [INFO] [main] [message: Agent running on a Swarm cluster node. Running in cluster mode]
2019/11/12 15:04:36 [INFO] serf: EventMemberJoin: tethys-d77182e7507e 10.0.5.7
2019/11/12 15:04:36 [INFO] serf: EventMemberJoin: atlas-e2d118f82a55 10.0.5.3
2019/11/12 15:04:36 [INFO] serf: EventMemberJoin: titan-499886d03a92 10.0.5.5
2019/11/12 15:04:36 [INFO] serf: EventMemberJoin: ganymede-565f285dfcd6 10.0.5.4
2019/11/12 15:04:47 [INFO] [http] [server_addr: 0.0.0.0] [server_port: 9001] [secured: true] [api_version: 1.5.1] [message: Starting Agent API server]
```

They are on the same network and i've launched a container connected on the portainer agent network and did a nslookup on tasks.portainer_agent, all ip's show up

**Technical details:**
* Portainer version: agent/latest
* Docker version: 19.03.4
* Platform (windows/linux): linux
* Browser: n/a

**Comment by deviantony** [comment]
@xRmg Strange. It sounds like an issue within your Swarm/network. Can you start all the agents with the `-e LOG_LEVEL=DEBUG` parameter and give us the logs?

**Comment by xRmg** [comment]
It was an issue with my overlay network indeed,

I've reinitialized my cluster using --advertise-addr both on init (using the eth0 interface adress and not eth0:1 or other virtual interface) and on join (only specifying eth0, the workers dont have virtual nic's)
