### ISSUE TITLE
The --add-host option is ignored

### ISSUE THREAD

**Issue by soullivaneuh** [portainer/agent#104]
In order to register an agent trough a private network, I have to add the `--add-host` option like this:

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes -v /:/host --restart always -e EDGE=1 -e EDGE_ID=xxx-xxx-xxx -e EDGE_KEY=XxX -e CAP_HOST_MANAGEMENT=1 -v portainer_agent_data:/data --name portainer_edge_agent --add-host=portainer.domain.io:10.10.200.101 portainer/agent
```

This is not working. It seems the agent is ignoring the host override and is still trying to fetch the public ip.

**Comment by deviantony** [comment]
Should work fine as the agent is simply doing a basic hostname resolution. This could be related to your Docker environment.

Please ensure this is working with other containers on your environment (such as a simple busybox container) and comment here with more details if you're still having the issue, I'll re-open in that case.
