### ISSUE TITLE
Add the ability to deploy a stack via Docker binary

### ISSUE THREAD

**Issue by deviantony** [portainer/agent#112]
Add support for Docker binary management to deploy a local stack.

**Comment by deviantony** [comment]
- [ ] Blocked by #111

**Comment by chiptus** [comment]
Adding EdgeStackManager to either a new package `exec` (like in portainer) or the docker package.

EdgeStackManager should be able to do the following :
deploy a stack
remove a stack

**Comment by deviantony** [comment]
@chiptus yes we'll need to support private registries.

And also yes regarding endpoints, we only need to support communication with the local socket as the docker binary is embedded inside the agent image (and the agent already has access to the socket on deployment).

**Comment by deviantony** [comment]
Closed via #113
