### ISSUE TITLE
enable skipping of compiling in dev script

### ISSUE THREAD

**Issue by chiptus** [portainer/agent#118]
sometimes I want to run the dev script without compiling because my code is already built, but I want to deploy it (for example, run on local and then on swarm)

I propose adding a third argument that is a boolean:
`./dev.sh MODE SKIP_COMPILE`
for example: `./dev.sh swarm true`

in addition, I think mode should have a default so we can run `./dev.sh`. I use mostly swarm, but the default depends on what's mostly in use.

**Comment by deviantony** [comment]
Closed via #119
