### ISSUE TITLE
Introduce support for Edge job log collection

### ISSUE THREAD

**Issue by deviantony** [portainer/agent#135]
Related to the work on Edge jobs in https://github.com/portainer/portainer/issues/3745

Add the ability to report back Edge job logs to the Portainer instance.

**Comment by chiptus** [comment]
there're a few tasks for this one:
- [ ] get which jobs need their log collected.
- [ ] collect the logs and prevent double collection.
- [ ] send the logs back to the core.

my thoughts are like this:
- [ ] add an array of job id `collectLogs` to the object that is sent from the core when polling.
- [ ] create a service (logsCollector?) that will be similar to how the stacks manager works. it gets a list of ids and adds these to a queue that will be collected on its turn.
- [ ] inside the service we will have a coroutine that checks the queue every few seconds, if a job exists, it will collect its logs and send them to portainer and remove from queue.
