### ISSUE TITLE
support tls1.2+ and only recommended ciphers

### ISSUE THREAD

**Issue by chiptus** [portainer/agent#145]
related to https://github.com/portainer/portainer/issues/2359

**Comment by deviantony** [comment]
Note: this fix should be applied against the `1.6.1` branch and will be backported into the version 2.0

**Comment by deviantony** [comment]
See my point in https://github.com/portainer/portainer/issues/2359#issuecomment-655243601 we should actually use TLS 1.3 on the agent.

**Comment by deviantony** [comment]
Closed via #146

**Comment by deviantony** [comment]
Re-opening as we're having issues when deploying stacks through the docker binary on an agent enabled endpoint (docker binary cannot use TLS 1.3).

We're gonna apply the same patch as for the Portainer server then, TLS 1.2 + recommended ciphers.

cc @chiptus

**Comment by deviantony** [comment]
Closed via #147
