### ISSUE TITLE
Improve Agent Security

### ISSUE THREAD

**Issue by Trufax** [portainer/agent#200]
Dear Team,

i would like to understand if it is possible to increase the security of the portainer agent:

At the moment we have 2 Options:
1. Portainer Agent only accepts the first instance connecting to it (TOFU). The issue here is that if the Portainer Agent is updated eg. via watchtower there is a window of time an attacker could connect first and take over the agent after an update.
2. Use the shared secret. The issue here is that the shared secret is static so an attacker gaining access to the secret (eg on one of the nodes) could take over all other agents by connecting a second instance with the shared secret.

Is ist possible to combine both (the TOFU approach) and add the shared secret in addition for the first connection ? So you could use the benefits of both features. 

Or is there a way to use multiple agent secrets ?

Regards

Trufax

**Comment by deviantony** [comment]
Hi @Trufax 

There is no way to combine both at the moment and I don't see how we could combine both of these features or the increase in security that it would bring?

**Comment by Trufax** [comment]
Hello,

ofc it doesn't make sense to have both in parallel all the time. I would see an approach like a "first contact secret" which is used for the first authentication. After that the TOFU approach is used. This would mitigate the issue that during a update procedure some attack could sneak in its own instance of portainer.
