### ISSUE TITLE
edge agent  : Missing request signature headers (err=Unauthorized) (code=403)

### ISSUE THREAD

**Issue by xywf221** [portainer/agent#217]
I follow exactly `edge_agent_guide.pdf` for operation.

1.Copy command and Execute the command 
2.Home page refresh
3.Click edge agent Endpoint

I saw warning : Failure Endpoint is unreachable and there is no snapshot available for offline browsing.

this is logs portainer server ip hidden by me
```
root@ubuntu:~# docker logs portainer_edge_agent
2021/11/20 13:39:41 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2021/11/20 13:39:41 [INFO] [main] [message: Agent running on Docker platform]
2021/11/20 13:39:41 [INFO] [main,edge] [message: Edge key loaded from options]
2021/11/20 13:39:41 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.10.0] [message: Starting Agent API server]
2021/11/20 13:40:01 client: Connecting to ws://????:8000
2021/11/20 13:40:02 client: Fingerprint ba:29:b9:d8:97:ea:db:c7:9e:32:16:43:0d:fc:25:90
2021/11/20 13:40:02 client: Connected (Latency 159.956772ms)
2021/11/20 13:40:10 http error: Missing request signature headers (err=Unauthorized) (code=403)
2021/11/20 13:40:57 http error: Missing request signature headers (err=Unauthorized) (code=403)
2021/11/20 13:45:25 http error: Missing request signature headers (err=Unauthorized) (code=403)
2021/11/20 13:45:27 http error: Missing request signature headers (err=Unauthorized) (code=403)
```

**Comment by schmitzCatz** [comment]
Hi,

Something does not work right using the latest edge agent. I upgraded portainer already but his did not fix the problem. Downgrading the edge agent to version 2.1.0 did the trick for me. Looks like API`s are incompatible:

latest seems to use 2.10.0 version:
`2021/11/21 11:47:44 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.10.0] [message: Starting Agent API server]`

2.1.0 uses 2.0.0 version:
`2021/11/21 11:50:08 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.0.0] [message: Starting Agent API server]
`

Regards,

Oliver

**Comment by xywf221** [comment]
> Hi,
> 
> Something does not work right using the latest edge agent. I upgraded portainer already but his did not fix the problem. Downgrading the edge agent to version 2.1.0 did the trick for me. Looks like API`s are incompatible:
> 
> latest seems to use 2.10.0 version: `2021/11/21 11:47:44 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.10.0] [message: Starting Agent API server]`
> 
> 2.1.0 uses 2.0.0 version: `2021/11/21 11:50:08 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.0.0] [message: Starting Agent API server] `
> 
> Regards,
> 
> Oliver

Thank you for your reply. I'll try

**Comment by huib-portainer** [comment]
Did you upgrade both Portainer and the Edge Agent to EE-2.10.0?
(it's important that they both get upgraded as per https://docs.portainer.io/v/be-2.10/release-notes)

**Comment by schmitzCatz** [comment]
> Did you upgrade both Portainer and the Edge Agent to EE-2.10.0? (it's important that they both get upgraded as per https://docs.portainer.io/v/be-2.10/release-notes)

I'm using the Community Edition, maybe that's the problem. It looks like the agents are already on api version 2.10 and the community edition of portainer is stuck at 2.9

**Comment by huib-portainer** [comment]
It's the same for CE when upgrading to CE-2.9.3.
(it's important that both the Portainer instance and the Edge Agent get upgraded at the same time as per the release notes: https://github.com/portainer/portainer/releases/tag/2.9.0)

And both CE and EE use the same agent, so that in itself shouldn't be a problem.

**Comment by schmitzCatz** [comment]
> It's the same for CE when upgrading to CE-2.9.3. (it's important that both the Portainer instance and the Edge Agent get upgraded at the same time as per the release notes: https://github.com/portainer/portainer/releases/tag/2.9.0)
> 
> And both CE and EE use the same agent, so that in itself shouldn't be a problem.

can confirm using CE-2.9.3 with latest agent is working properly. Thank you.

**Comment by xywf221** [comment]
I completely removed the portal and reinstalled the latest version to solve this problem
