### ISSUE TITLE
Image import doesn't work

### ISSUE THREAD

**Issue by KoakiMiku** [portainer/agent#222]
![Snipaste_2021-12-07_16-59-24](https://user-images.githubusercontent.com/34326561/144998263-67e377d1-f5d0-49d8-953f-fba4676927ae.png)

I can't import image on some server.

![Snipaste_2021-12-07_16-54-07](https://user-images.githubusercontent.com/34326561/144997448-5041fdbc-69e0-4bad-88e1-df51cd04d710.png)

When import was working, I can see error in logs.

![Snipaste_2021-12-07_16-56-31](https://user-images.githubusercontent.com/34326561/144997795-a68de3bc-6f66-4c6a-bf7c-09ad444e0272.png)

**Comment by KoakiMiku** [comment]
Ubuntu 20.04
Docker Standalone 20.10.11
portainer/portainer-ce:2.9.3
portainer/agent:2.9.3

**Comment by huib-portainer** [comment]
Are you able to provide the rest of that error message, around `Unable to retrieve DockerHub token`?

**Comment by KoakiMiku** [comment]
How can I get more detailed logs?

**Comment by KoakiMiku** [comment]
I upgrade to 2.11.0 and it seems to be fixed.
