### ISSUE TITLE
edge agent won't connect anymore

### ISSUE THREAD

**Issue by tedstriker** [portainer/agent#242]
### Problem
One of my edge agents stopped connecting to the portainer instance. The edge agents log is filled with
`[ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]`
Two other edge agents still connect properly.
The portainers logs shows nothing.
Version of portainer and edge agent 2.11.0

### Expected behaviour
connect to portainer instance

### Unsuccessful fixing attempts so far
- removing edge agent container and volume and redeploying it
- checking certificate date not being expired -> valid
- checking connection with `nc portainer.example.com 8000` -> works
- de-associate environment config
- create a new environment config
  - Interestingly having the edge agent deployed with the new edge id and edge key, while removing the config from portainer afterwards rises an error in portainer
  `http error: A valid authorisation token is missing (err=Unauthorized) (code=401)"`
  which indicates that the edge agent actually connects but receives some unexpected response from portainer.
- google extensively
- turn on debug mode on edge agent -> doesn't provide any more valuable information

Any hint how to gather further debug information, how to interpret the single error line or at best how to fix this issue is highly appreciated

**Comment by deviantony** [comment]
@tedstriker could you isolate the DEBUG logs around the error message?

Anything +10-10l around `[ERROR] [internal,edge,poll] [message: an error occured during short poll]`, it can be helpful to troubleshoot from our side.

This sounds like a JSON decoding issue. From the top of my mind these could happen because of the following:

* Invalid format/character in an Edge job associated to that environment
* Invalid format/character in an Edge stack associated to that environment (less likely than Edge Job)

I would try to clean-up any Edge stacks/Edge jobs associated to that environment first to see if you're still having this issue.

Next I would try to query the Portainer API directly by simulating a short poll request:

Note: this example is using https://httpie.io/

```
# --verify=no is optional if your instance is not using self-signed certs
http --verify=no https://<MY_PORTAINER_IP>:9443/api/endpoints/<ENVIRONMENT_ID>/status "X-PortainerAgent-EdgeID: <AGENT_EDGE_ID>"
```

Replace the parameters in the query above with:
* MY_PORTAINER_IP: IP/URL of your Portainer instance
* ENVIRONMENT_ID: Id of the environment in Portainer (can be retrieved from the URL when inspecting the environment in the environments view)
* AGENT_EDGE_ID: Available when inspecting the environment in the environments view

**Comment by tedstriker** [comment]
Thank you for your help.

> This sounds like a JSON decoding issue. From the top of my mind these could happen because of the following:
> 
> Invalid format/character in an Edge job associated to that environment
> Invalid format/character in an Edge stack associated to that environment (less likely than Edge Job)

I was working on an edge stack that day, so I considered a parsing error, too. To address that I created a new edge environment config, deleted the old container and it's volume on the remote system and spun up a new one with the new `EDGE_KEY` and `EDGE_ID`. So it should have no relation to a maybe faulty stack, but still got the error.
Besides that I don't know how to clean up stacks of an egde agent, which is not connecting anymore. I tried deleting the related compose file in the portainer instance' data directory. Same result. Maybe further steps are necessary.

Querying the portainer API using
`curl -i -H "X-PortainerAgent-EdgeID: <AGENT_EDGE_ID>" -H "Portainer-Agent-Platform: 0" https://<MY_PORTAINER_IP>:9443/api/endpoints/<ENVIRONMENT_ID>/status`

returned the following result. Actually it did for every other endpoint as well.
```
HTTP/2 200 
content-type: application/json
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-length: 83
date: Tue, 15 Feb 2022 13:13:37 GMT

{"status":"IDLE","port":0,"schedules":[],"checkin":5,"credentials":"","stacks":[]}
```

### Log
I restarted the container, so you can see the log from the very beginning.
```
2022/02/15 12:34:09 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2022/02/15 12:34:09 [INFO] [main] [message: Agent running on Docker platform]
2022/02/15 12:34:09 [INFO] [main,edge] [message: Edge key loaded from options]
2022/02/15 12:34:09 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.11.0] [message: Starting Agent API server]
2022/02/15 12:34:15 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:20 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:25 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:30 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:35 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:40 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:45 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:50 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/15 12:34:55 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]

and so on
```

**Comment by deviantony** [comment]
@tedstriker thanks for the feedback! Could you redeploy the Portainer agent with the `-e LOG_LEVEL=debug` parameter? That would give us access to DEBUG logs.

**Comment by tedstriker** [comment]
I found the reason why it stopped working. On the same day I cleaned the config of a reverse proxy and `PORTAINER:9443` wasn't accessible afterwards for the then faulty edge agent. I falsely considered the reverse proxy configuration entry to be a left over of a test.
Consulting this [guide](https://downloads.portainer.io/edge_agent_guide.pdf) wasn't helping as much as it could. It puts so much emphasis on port 8000 to be exposed, I considered it to be the only port to be forwarded.

#### Solution
Expose port 8000 AND 9443 to every edge agent.
Again a reminder to only change one thing at a time. :)

Thank you for your help guys :)

here's the debug log, after restart till repeating entries occur. It might help others to identify similar issues.
```
2022/02/16 06:19:42 [WARN] [os,options] [message: the CAP_HOST_MANAGEMENT environment variable is deprecated and will likely be removed in a future version of Portainer agent]
2022/02/16 06:19:42 [INFO] [main] [message: Agent running on Docker platform]
2022/02/16 06:19:42 [DEBUG] [main,configuration] [Member tags: &{AgentPort:9001 EdgeKeySet:false NodeName:localhost DockerConfiguration:{EngineStatus:1 Leader:false NodeRole:0} KubernetesConfiguration:{}}]
2022/02/16 06:19:42 [DEBUG] [docker] [ip_address: 172.17.0.2] [network_name: bridge] [message: Retrieving IP address from container network]
2022/02/16 06:19:42 [INFO] [main,edge] [message: Edge key loaded from options]
2022/02/16 06:19:42 [DEBUG] [main,edge] [message: Edge key found in environment. Associating Edge key]
2022/02/16 06:19:42 [DEBUG] [internal,edge] [api_addr: 172.17.0.2:9001] [edge_id: 00000000-0000-0000-0000-000000000000] [poll_frequency: 5s] [inactivity_timeout: 5m] [insecure_poll: true]
2022/02/16 06:19:42 [DEBUG] [internal,edge,logs] [message: logs manager started]
2022/02/16 06:19:42 [DEBUG] [internal,edge,runtime,docker] [message: Docker runtime configuration check] [engine_status: 1] [leader_node: false]
2022/02/16 06:19:42 [DEBUG] [internal,edge,poll] [poll_interval_seconds: 5.000000] [server_url: https://portainer.example.com] [message: starting Portainer short-polling client]
2022/02/16 06:19:42 [DEBUG] [internal,edge,monitoring] [monitoring_interval_seconds: 30.000000] [inactivity_timeout: 5m0s] [message: starting activity monitoring loop]
2022/02/16 06:19:42 [INFO] [http] [server_addr: 172.17.0.2] [server_port: 9001] [secured: false] [api_version: 2.11.0] [message: Starting Agent API server]
2022/02/16 06:19:47 [DEBUG] [internal,edge,poll] [message: sending agent platform header] [header: 1]
2022/02/16 06:19:47 [DEBUG] [internal,edge,runtime,docker] [message: Docker runtime configuration check] [engine_status: 1] [leader_node: false]
2022/02/16 06:19:48 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/16 06:19:52 [DEBUG] [internal,edge,poll] [message: sending agent platform header] [header: 1]
2022/02/16 06:19:52 [DEBUG] [internal,edge,runtime,docker] [message: Docker runtime configuration check] [engine_status: 1] [leader_node: false]
2022/02/16 06:19:53 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/16 06:19:57 [DEBUG] [internal,edge,poll] [message: sending agent platform header] [header: 1]
2022/02/16 06:19:57 [DEBUG] [internal,edge,runtime,docker] [message: Docker runtime configuration check] [engine_status: 1] [leader_node: false]
2022/02/16 06:19:58 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: invalid character '<' looking for beginning of value]
2022/02/16 06:20:02 [DEBUG] [internal,edge,poll] [message: sending agent platform header] [header: 1]
```
