### ISSUE TITLE
Swarm Image Tag empty

### ISSUE THREAD

**Issue by Magi1053** [portainer/agent#272]
I have portainer agent installed on my docker swarm cluster on my manager and all nodes. I have several images that display in the portainer dashboard as having no tag. I can also not export these images with error `Cannot download a untagged image`

![chrome_96IHte9PUu](https://user-images.githubusercontent.com/1045179/158466777-11dc5158-33e7-4804-8f6e-3ebc8fc7e4c8.png)

**Comment by jamescarppe** [comment]
This generally happens when an updated version of that image and tag is pulled, and Docker untags the old version of the image. We are looking at what we can do around this as part of other issues, but at present this is an artifact of how Docker itself does things.
