### ISSUE TITLE
Portainer Agent Version

### ISSUE THREAD

**Issue by stevefxp1** [portainer/agent#311]
Hello all,

Is there a way to identify the version of the agent running on a machine? Is this information within the Portainer GUI or is there a CLI to identify this?

Thanks,
Steve

**Comment by deviantony** [comment]
@stevefxp1 we're working on bringing this information in a future release of Portainer to identify the agent version directly in the UI.

In the meantime, the only way to check an agent version would be to check the image used by the agent or check the logs when the agent starts as it will output which version it is using.
