### ISSUE TITLE
Edge agent does not work when the portainer server is accessed through a CNAME record

### ISSUE THREAD

**Issue by npenin** [portainer/agent#351]
If the portainer server is accessed through a CNAME record (portainer.example.com), the edge agent is not able to contact the server:

```
[edge] [message: an error occured during short poll] [error: Get "https://portainer.example.com:9443/api/endpoints/4/edge/status": dial tcp: lookup portainer.example.com on 10.68.8.1:53: no such host]
```

The nslookup from the host works though:
```
nicolas@xps139300 ~ % nslookup portainer.example.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
portainer.example.com       canonical name = azure.example.com.
azure.example.com   canonical name = xxx.westeurope.cloudapp.azure.com.
Name:   xxx.westeurope.cloudapp.azure.com
Address: YYY.YYY.YYY.YYY
```

**Comment by deviantony** [comment]
@npenin this could simply be related to DNS not properly propagating in your Docker containers by the Docker daemon, usually restarting the container would fix that issue.

**Comment by npenin** [comment]
unfortunately not, I even dropped the container to re-register the agent with a brand new token, without success.

**Comment by npenin** [comment]
Sorry, that was actually a wrong configuration on my local intranet. :blush:
