### ISSUE TITLE
Older docker-compose version replaces all containers  when only one changed

### ISSUE THREAD

**Issue by smitb** [portainer/agent#471]
Hi,

We encounter an issue when we have a change on one container in a compose stack, all containers are replaced on the host when we apply the stack. This is fixed in a newer docker-compose version. This version seems to be already in the develop branch.

https://github.com/portainer/agent/blob/develop/setup.sh

When will this be merged and released?

Background info: The issue in docker compose is fixed here: https://github.com/docker/compose/issues/9600#issuecomment-1489013639

Thanks,

Bas

**Comment by jamescarppe** [comment]
Fixed in https://github.com/portainer/portainer/issues/9095/.
