### ISSUE TITLE
Agent takes a while to acknowledge that another agent is unavailable

### ISSUE THREAD

**Issue by itsconquest** [portainer/agent#56]
Related to: https://github.com/portainer/portainer/issues/2938

**Comment by deviantony** [comment]
After investigation, it takes around 5 seconds in my environment for a dead agent to be marked as down. It is more than enough in my opinion.

**Comment by deviantony** [comment]
In my opinion, the actual behavior to spot a failed agent is OK. I'll update another issue related to my comment above to prevent this reconnect behavior.
