### ISSUE TITLE
Load default value for advertise address automatically

### ISSUE THREAD

**Issue by deviantony** [portainer/agent#70]
In order to provide an easier way to deploy the agent (less parameters) and to prevent configuration errors related to providing an invalid value to the currently mandatory `AGENT_CLUSTER_ADDR`, it should be possible to leverage the container labels to retrieve the name of the service associated to the container.

This information is available under the `com.docker.swarm.service.name` container label which is present when deploying the agent as a service or via a Swarm stack.

For legacy deployments via containers such as hybrid Linux/Windows deployments requiring the agent to run as a container attached to an overlay network on Windows nodes, this option should still be available.

If specified the value of `AGENT_CLUSTER_ADDR` should override the default retrieved from the label.

**Comment by SvenDowideit** [comment]
I want to be able to tell an agent to _ignore_ the fact its running on a node that is part of a swarm.

**Comment by deviantony** [comment]
See my answer in https://github.com/portainer/agent/issues/70#issuecomment-526021739 for the discussion about your use case. Your request is not related to this issue.
