### ISSUE TITLE
Error even though variable is set. [message: AGENT_CLUSTER_ADDR environment variable is required when deploying the agent inside a Swarm cluster] 

### ISSUE THREAD

**Issue by scyto** [portainer/agent#94]
**Bug description**
I am getting these errors despite, i think, setting the ENV VAR correctly in the stack file; this is resulting in many restarts and container creations and deletions - basically an infinite loop.  These logs were pulled from the service logs UI in portainer (attached as local). 

`2019/10/09 05:19:13 [INFO] [main] [message: Agent running on a Swarm cluster node. Running in cluster mode],
2019/10/09 05:19:13 [ERROR] [main,configuration] [message: AGENT_CLUSTER_ADDR environment variable is required when deploying the agent inside a Swarm cluster],
2019/10/09 05:19:23 [INFO] [main] [message: Agent running on a Swarm cluster node. Running in cluster mode],
2019/10/09 05:19:23 [ERROR] [main,configuration] [message: AGENT_CLUSTER_ADDR environment variable is required when deploying the agent inside a Swarm cluster],`

**Expected behavior**
I expected it to work and not get this error given i did set the AGENT_CLUSTER_ADDR in the stack file and 95% certain i got the synatx right, this may also explain why the curl and manual methods resulted in may restarts.

**Steps to reproduce the issue:**
1. Install portainer on synology
2. create symlink /var/lib/docker/volumes > /volume3/@docker/volumes (this is where they are located on synology - volumeN/@docker where N is the volume number)
3. create a swarm with docker command line tools
3. try and deploy this stack via portainer UI calling the stack 'agent' resulting in a service name of agent_agent

```version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent_agent
      AGENT_SECRET: mysecrettoken
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer_agent:
    driver: overlay
    attachable: true
```

**Technical  agent: 
latest as of 10.8.2019

* Docker version (managed by Portainer):
Server Version: 18.09.6
Storage Driver: btrfs

* Platform (windows/linux):
Linux (synology)
Portainer is working well.
Docker appears to be running ok as root.

Is there a way to run the agent as a standalone container (not part of a swarm, for testing purposes)?

**Comment by deviantony** [comment]
Hi @scyto 

I think this is an issue with Synology. Could be related to: https://github.com/portainer/portainer/issues/2423 (there is a link to a Synology bug report in that issue).

We're currently working on releasing a new version of the agent, you can use `portainerci/agent:develop` to try it (this version do not require the `AGENT_CLUSTER_ADDR` env var anymore).

In the same way, I believe that `AGENT_SECRET` is gonna be ignore on your platform.

**Comment by scyto** [comment]
@deviantony thanks, will give the dev version a go, interesting about the other ticket - in general I have had no issues with `docker run -e `  commands via SSH; though this is my first time using yaml files and making docker part of a swarm - i will read the ticket and see if there is anything i can help track down...

**Comment by scyto** [comment]
@deviantony an update: yes that allowed it work and you are right no env vars are being propogated.  I also had an issue where my manager swam node advertised address and listening address were not the same, the listening was a real IP, the advertised was an internal docker 10.x that was not reachable across hosts (my portainer is basic install and not in swarm) i fixed by recreating the swarm using --advertise-addr and --listen-addr to force both IPs to be my real LAN IPs.  What was interesting was the agent deployed to host2 but couldn't find the manager.  Also i made both nodes managers.

As such can close by saying fixed in upcoming. 
I will monitor the env var bug.
Should i bug the IP address behaviour or do we consider that mis-config of swarm?

**Comment by deviantony** [comment]
@scyto glad it works now, for the other one it's a Swarm misconfiguration.

**Comment by scyto** [comment]
@deviantony FYI the issue doesn't appear to be a docker-compose issue on synology. Docker-compose is working fine.  There may be issue with docker service create not passing env vars...

**Comment by deviantony** [comment]
Try to isolate if this is a platform related issue (Synology).

**Comment by scyto** [comment]
@deviantony i had no other platform, until i joined windows docker desktop to the swarm - thanks for encouraging me to play and learn!  any hoo the test service container got created on the windows docker desktop as soon as it joined the swarm (along with agent!) the container has the VAR set - definitely a synology platform issue.  I have an open ticket with synolgy on the issue.  Question - does portainer pass docker commands using the docker CLI or does it call an API directly?

**Comment by deviantony** [comment]
@scyto it calls the API directly.

**Comment by scyto** [comment]
thanks i won't bother progressing a thought that it might be an issue with the docker cli exec then :-) - if i get an answer from synology i will let you know, this is definitely not a portainer issue.

**Comment by scyto** [comment]
official synology response:

```It looks like this is most likely being caused by the swarm function of the Docker, which is an issue that our developers are aware of. They are working on a fix, and it should be available in a future release, but there is no workaround in the meantime.``

**Comment by scyto** [comment]
Official Synology response:

```It looks like this is most likely being caused by the swarm function of the Docker, which is an issue that our developers are aware of. They are working on a fix, and it should be available in a future release, but there is no workaround in the meantime.```
